name: leer archivo xml
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10'

      - name: Ejecuta Python
        run: python .github/workflows/ejecuta.py    
