name: leer archivo xml
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
    
      - name: Ejecuta Python
        run:  python .github/workflows/ejecuta.py    