on: 
  push:
    branches:
      - main
name:  deployar en mi website con push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: sundarasaludybelleza.com.mx
        username: ${{ secrets.ftp_usuario }}
        password: ${{ secrets.ftp_password }}
        server-dir: /home/sunda412/belleza.sundarasaludybelleza.com.mx
